### ISSUE TITLE
Database - structure

### ISSUE THREAD

**Issue by julienkessels** [martinmatin/KitBox#11]
Define the structure

**Comment by martinmatin** [comment]
![image](https://cloud.githubusercontent.com/assets/15802841/23121199/c1bc5df8-f75f-11e6-85f7-d2185d15355e.png)
First version. Any modifications ?

**Comment by martinmatin** [comment]
![image](https://cloud.githubusercontent.com/assets/15802841/23122438/83772000-f764-11e6-9cf7-bb6ec2cdcbe8.png)
The xlsx file:
[Classeur1.xlsx](https://github.com/martinmatin/KitBox/files/787227/Classeur1.xlsx)

**Comment by CasCh174** [comment]
Changes to apply:
   -'Commande' to 'Commandes'
   -A client will be able to give his adress so we have to provide a field for that

**Comment by CasCh174** [comment]
tables are done.
still to:
   -code which generates these tables on any other computer
   -functions related to the database ( @benjvdb9 )
   -to myself: change 'stock->code->varchar(20)' to 'stock->code->enum' (if it works)

**Comment by julienkessels** [comment]
Nice. Take a look @ https://github.com/julienkessels/Techno_Web/blob/master/index.php for an implementation example for the table generation

**Comment by julienkessels** [comment]
@CasCh174 When you're done, push your code here and I will close the Issue for the structure an create a new one for the functions.

**Comment by martinmatin** [comment]
Up date modifications on the excel
