### ISSUE TITLE
Activity diagram, business focused (cabinet selling)

### ISSUE THREAD

**Issue by martinmatin** [martinmatin/KitBox#3]
Do not hesitate to share your diagram.

**Comment by benjvdb9** [comment]
Here's the first draft of the activity diagram. If this isn't what you expected the diagram to look like, if you think that the program would function differently, or if some small changes need to be made do tell me. I could either make changes myself or share the file for others to modify.
![kitbox_activity](https://cloud.githubusercontent.com/assets/17020561/23073740/c14f58f0-f536-11e6-9baa-8168d06cfce5.png)

**Comment by martinmatin** [comment]
Seems to be okay for me.
Just one thing: Maybe that the user should login only after the program validated the command?
Something like this:
![image](https://cloud.githubusercontent.com/assets/15802841/23081222/20f50a1c-f554-11e6-93be-30bf37e5f72d.png)

**Comment by benjvdb9** [comment]
Possible, it wouldn't take to long to modify this but I originally had the client identify itself to make it easier to store the elements in the database. If we don't need the client ID when storing the data then I'll change it.

**Comment by martinmatin** [comment]
I see what you mean. Remember that we already discussed that and we thought that the ID used during the design session should be the ID of the order and not the client's one. At the end of the designing we will link the reservation's ID and the client's ID.

**Comment by benjvdb9** [comment]
In that case I'll be modifying the diagram and will upload it shortly

**Comment by julienkessels** [comment]
@benjvdb9 are you taking care of the "database not in the right place" problem ?

**Comment by benjvdb9** [comment]
![kitbox_activity](https://cloud.githubusercontent.com/assets/17020561/23497949/b70222a8-ff25-11e6-835a-d7c76913b5a1.png)
