### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by martinmatin** [martinmatin/KitBox#4]
Could you put a picture of your current diagram?

**Comment by benjvdb9** [comment]
Here's a base to work with. Just import the XML file in draw.io and it should work fine.
I'll share the xml file on facebook as github doesn't support XML.
![kitbox2](https://cloud.githubusercontent.com/assets/17020561/23066583/940a6990-f51b-11e6-9ad3-a8e4eb2860fe.png)

**Comment by martinmatin** [comment]
Nice job! Does @chrisskab  agree with you about the diagram ?
By way of reminder, do not generate the code yet until we (the team + the teachers) haven't validated it.

**Comment by benjvdb9** [comment]
There may still be some modifications to be done but I've sent the file to @chrisskab, otherwise it's pretty much the paper version with added variables and functions. I don't think we're even able to generate code at this point, but chris seemed to be looking into it.

**Comment by memesi** [comment]
I do indeed agree with the class diagram. However, some methods seem to be missing. Let's discuss it at our next meeting.

**Comment by benjvdb9** [comment]
![kitbox3](https://cloud.githubusercontent.com/assets/17020561/23118895/3d987d80-f756-11e6-93e5-acafe0021d00.png)

**Comment by martinmatin** [comment]
Looks great right now! Did mr Dkp see it ?

**Comment by memesi** [comment]
I added some modifications to the diagram:
1)I modified some properties
2)Traverse is now a class, not an interface. I figured while coding that using an interface doesn't bring anything.
3) Changed the overall shape of the diagram

![kitbox class diagram](https://cloud.githubusercontent.com/assets/17045198/23282464/9019f840-fa21-11e6-9167-5390b049468a.png)

Here is the link to the original io file: https://www.draw.io/#G0B1a0Pkc-6pC_MzJ3YXVDcnFzM0E

**Comment by memesi** [comment]
![kitbox class diagram 1](https://cloud.githubusercontent.com/assets/17045198/23467301/f6f23d9a-fe9d-11e6-97d0-60b617aeaa5c.png) 

1)Removed the "Text" Label on the Command-Client arrow
2)Added a use relation between client and Casier (Thanks to @CasCh174 for the remark)

Link to the io file: https://www.draw.io/#G0B1a0Pkc-6pC_MzJ3YXVDcnFzM0E

**Comment by CasCh174** [comment]
to do:
   - attributs syntax (ie. cammand_id)
   - English
   - number labels: one cabinet has 1 to 7 units
   - Base de Données to DatabaseManager
   -interface Element: reference is a string, code is a string, supplier is a list,

**Comment by memesi** [comment]
Here is the final version of the class diagram, updated according to the last version of the sequence diagram @CasCh174 posted:

![kitbox class diagram 4](https://cloud.githubusercontent.com/assets/17045198/23522008/b6348ae4-ff81-11e6-9fc0-be6dc767cad7.png)


 @julienkessels can you incorporate this in the intermediary report?

**Comment by martinmatin** [comment]
-[Order Manager] Delete <list>
-[Commande] list armoire to int armoire (multiplier)

**Comment by martinmatin** [comment]
-[Casier] add function: addElement
