### ISSUE TITLE
Uses cases diagram

### ISSUE THREAD

**Issue by martinmatin** [martinmatin/KitBox#5]

**Comment by memesi** [comment]
Here is the first version on the Use Case Diagram. Do not hesitate to give me a feedback on it or make some changes.
Here is the link to the original file: https://drive.google.com/file/d/0B1a0Pkc-6pC_RXYxVXJXUDRfQkk/view?usp=sharing

[Use Case Diagram.pdf](https://github.com/martinmatin/KitBox/files/786159/Use.Case.Diagram.pdf)

**Comment by memesi** [comment]
I updated the use case diagram. You can find the updated file on the original link.

**Comment by martinmatin** [comment]
For a clearer view: (thanks to @chrisskab )
![image](https://cloud.githubusercontent.com/assets/15802841/23139910/235dd736-f7af-11e6-956b-875947267e8e.png)

**Comment by julienkessels** [comment]
We've got approval for the Case diagram, I'm closing this for now.
