### ISSUE TITLE
User Interface Mockup

### ISSUE THREAD

**Issue by martinmatin** [martinmatin/KitBox#6]
https://drive.google.com/drive/folders/0BzTo45U3V8PrWlhxYUo1czMzRlE

**Comment by martinmatin** [comment]
@julienkessels First mockup of the home page

https://drive.google.com/file/d/0BzTo45U3V8PrTnMyRi1hM3JlZlU/view?usp=sharing

**Comment by julienkessels** [comment]
Looks great, trying it out tonight in the app ! P.s What should we use as standard window size ?

**Comment by julienkessels** [comment]
@martinmatin Could you please try to add transparent .png file of a shelf? I'll try to figure out how to implement it in the code. Thanks buddy

**Comment by martinmatin** [comment]
https://drive.google.com/file/d/0BzTo45U3V8PrZWhyWTUtekZTVkE/view?usp=sharing, the shelf.
Moreover, you can have a look to the folder of google drive, there's everything you need to work on the UI. The folder for the next 'view' is coming. I'm working on it.

**Comment by martinmatin** [comment]
The general parameters view:
https://drive.google.com/drive/folders/0BzTo45U3V8PreXVHM0gyNFFwTnM?usp=sharing

**Comment by martinmatin** [comment]
@julienkessels Tell what you think about it:
If it is ok, i'll edit all the PNG you need (background, buttons,...)
![pg2](https://cloud.githubusercontent.com/assets/15802841/23047514/a93df3ce-f4b0-11e6-97e3-5bc7befa22be.png)

**Comment by julienkessels** [comment]
Yeah i think its all fine ;)

**Comment by memesi** [comment]
Looks great Martin!

**Comment by julienkessels** [comment]
To add on pg3:
-Info
-Sames as
-Delete

**Comment by julienkessels** [comment]
To add on home page:
-Delete the button
-Generate a new background without the button
-Delete the "home" frame

**Comment by martinmatin** [comment]
I Will do this tonight.

**Comment by martinmatin** [comment]
The new home's background is available on the Drive folder!

**Comment by martinmatin** [comment]
Some parts of the second page are available on the Drive

**Comment by julienkessels** [comment]
- Can you please remove the top bar
- Text

**Comment by martinmatin** [comment]
- Delete the checkBox on leftBar pg1
- Delete Button
- Back button
- Validate button

**Comment by martinmatin** [comment]
Pg3 done .

**Comment by martinmatin** [comment]
The graphic design is finished and can be accessed from the Drive.
