### ISSUE TITLE
User interface implementation

### ISSUE THREAD

**Issue by martinmatin** [martinmatin/KitBox#7]

**Comment by julienkessels** [comment]
@martinmatin I pushed an update!

**Comment by martinmatin** [comment]
Nice work, is it possible to apply color change when the buttons are hovered?

**Comment by julienkessels** [comment]
@CasCh174 taking care of the DB
@martinmatin taking care of the image generation

@chrisskab Could you please check for me what possibilities i have for the cabinet's depth/width. If I can use any combination i want or if for some depths i can only chose certain widths. That is needed for page1. 

For page2 we'll be asking for a wanted height for each shelf. Can you please check them for me too? And here too, check if there are some limitations I need to be aware of.. Certain combinations i can't have.. 

Thanks!

The result could be a list like this : avialable depths : 32,42,...
                                                       available widths : 32,42,...
                                                       etc

**Comment by julienkessels** [comment]
Please checkout the progress, and alert me if something has to be changed!

**Comment by martinmatin** [comment]
Everything is up to date on the drive now

**Comment by martinmatin** [comment]
It seems that we can close this section. UI is finished and look good.
